### ISSUE TITLE
Feature request: Parallax effect

### ISSUE THREAD

**Issue by iTob191** [Nauviax/visible-planets#4]
The stars in the background have a parallax effect: When you move the screen, the stars in the background move slower than the space ship in the foreground to create the illusion that the stars are further away. Currently, the planet sprite moves at the same rate as the foreground. My suggestion is to add a parallax effect similar to the one already present for stars.

And btw, thanks for the great mod!

**Comment by Nauviax** [comment]
This was brought up earlier on the mod portal. I'd love to do this, but the star's parallax effect is hard coded and not something I can just add to the planet render.

I've experimented with a few options, but nothing has worked properly yet. For example, simply moving the planet when the camera moves would work, but might be bad for performance and would instantly break in multiplayer.

**Comment by Nauviax** [comment]
So I ended up doing a 180 and implemented parallax anyway. It's not perfect, and very funky in multiplayer, but it does the job well enough.
